// ─── DO NOT EDIT THIS FILE ────────────────────────────────────────────────────
//
// The production Service Worker for Joy's Kitchen is generated automatically
// by vite-plugin-pwa (Workbox) during `npm run build`.
//
// The generated file (sw.js / workbox-*.js) is written to the dist/ folder and
// handles:
//   • Pre-caching of the app shell
//   • Runtime caching strategies (fonts, images, Firebase SDK)
//   • Offline fallback to index.html
//   • Push notification display
//   • Notification-click → focus/open window
//
// Caching rules are configured in vite.config.js under the `workbox:` key.
//
// To customise SW behaviour beyond what Workbox exposes, set
//   strategies: "injectManifest"
// in vite.config.js and provide a src/sw.js file instead.
// ─────────────────────────────────────────────────────────────────────────────
