import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App.jsx";

// Register service worker (generated by vite-plugin-pwa)
import { registerSW } from "virtual:pwa-register";

registerSW({
  onNeedRefresh() {
    // A new version is available — you can show a toast/prompt here.
    // For now we auto-update silently. To prompt the user instead,
    // call updateSW() after showing a "New version available" banner.
    console.info("[PWA] New content available, updating…");
  },
  onOfflineReady() {
    console.info("[PWA] App is ready to work offline.");
  },
  // Reload the page automatically when a new SW takes control
  immediate: true,
});

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <App />
  </StrictMode>
);
